# Generated by Django 3.2.4 on 2021-11-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
