# Generated by Django 3.2.4 on 2021-11-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='emp_id',
        ),
    ]
